// PDF Intelligence Report Generator
// Compiles analysis into a structured, presentation-ready document

import jsPDF from "jspdf";
import "jspdf-autotable";

export function generateReport(analysisData) {
	const {
		kpis,
		anomalies,
		correlations,
		forecasts,
		insights,
		schema,
		fileName,
		rowCount,
	} = analysisData;

	const doc = new jsPDF("p", "mm", "a4");
	const pageWidth = doc.internal.pageSize.getWidth();
	const margin = 20;
	const contentWidth = pageWidth - margin * 2;
	let y = margin;

	// Colors
	const brandColor = [51, 129, 255];
	const darkBg = [15, 23, 42];
	const textPrimary = [30, 41, 59];
	const textSecondary = [100, 116, 139];

	// --- Cover Page ---
	doc.setFillColor(...darkBg);
	doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), "F");

	doc.setFillColor(...brandColor);
	doc.rect(margin, 40, 60, 3, "F");

	doc.setTextColor(255, 255, 255);
	doc.setFontSize(28);
	doc.setFont("helvetica", "bold");
	doc.text("Yukti Intelligence Report", margin, 60);

	doc.setFontSize(12);
	doc.setFont("helvetica", "normal");
	doc.setTextColor(148, 163, 184);
	doc.text("Autonomous Decision Intelligence Analysis", margin, 72);

	doc.setFontSize(10);
	doc.text(`Dataset: ${fileName}`, margin, 95);
	doc.text(`Records Analyzed: ${rowCount?.toLocaleString()}`, margin, 103);
	doc.text(`Features Detected: ${schema.columns.length}`, margin, 111);
	doc.text(
		`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
		margin,
		119,
	);

	doc.setFontSize(9);
	doc.setTextColor(100, 116, 139);
	doc.text(
		"This report was autonomously generated by Yukti Decision Intelligence Engine.",
		margin,
		145,
	);
	doc.text(
		"All metrics, insights, and forecasts are derived through automated statistical analysis.",
		margin,
		153,
	);

	// --- Dataset Summary Page ---
	doc.addPage();
	y = addSectionHeader(doc, "Dataset Summary & Schema Profile", margin, margin);

	doc.setFontSize(10);
	doc.setTextColor(...textPrimary);
	doc.setFont("helvetica", "normal");

	const numericCols = schema.columns.filter(
		(c) => schema.types[c] === "numeric",
	);
	const categoricalCols = schema.columns.filter(
		(c) => schema.types[c] === "categorical",
	);
	const temporalCols = schema.columns.filter(
		(c) => schema.types[c] === "temporal",
	);

	y += 5;
	doc.text(
		`Total Features: ${schema.columns.length}  |  Numeric: ${numericCols.length}  |  Categorical: ${categoricalCols.length}  |  Temporal: ${temporalCols.length}`,
		margin,
		y,
	);
	y += 10;

	// Schema table
	const schemaRows = schema.columns.map((col) => {
		const s = schema.summary[col];
		return [
			col,
			schema.types[col],
			String(s.nonNull),
			String(s.uniqueCount),
			s.type === "numeric"
				? s.mean?.toFixed(2)
				: s.type === "temporal"
					? s.spanDays + " days"
					: s.topValues?.[0]?.[0] || "-",
		];
	});

	doc.autoTable({
		startY: y,
		head: [["Feature", "Type", "Non-Null", "Unique", "Key Stat"]],
		body: schemaRows,
		margin: { left: margin, right: margin },
		styles: { fontSize: 8, cellPadding: 3 },
		headStyles: { fillColor: brandColor, textColor: [255, 255, 255] },
		alternateRowStyles: { fillColor: [248, 250, 252] },
	});

	y = doc.lastAutoTable.finalY + 15;

	// --- KPI Summary ---
	if (kpis.length > 0) {
		if (y > 230) {
			doc.addPage();
			y = margin;
		}
		y = addSectionHeader(doc, "Key Performance Indicators", margin, y);
		y += 5;

		const kpiRows = kpis
			.slice(0, 10)
			.map((kpi) => [
				kpi.label,
				formatNumber(kpi.current),
				`${kpi.change > 0 ? "+" : ""}${kpi.change}%`,
				kpi.trend,
				`${(kpi.confidence * 100).toFixed(0)}%`,
				`${kpi.volatility}%`,
			]);

		doc.autoTable({
			startY: y,
			head: [
				["Metric", "Current", "Change", "Trend", "Confidence", "Volatility"],
			],
			body: kpiRows,
			margin: { left: margin, right: margin },
			styles: { fontSize: 8, cellPadding: 3 },
			headStyles: { fillColor: brandColor, textColor: [255, 255, 255] },
			alternateRowStyles: { fillColor: [248, 250, 252] },
		});

		y = doc.lastAutoTable.finalY + 15;
	}

	// --- Anomalies ---
	if (anomalies.length > 0) {
		if (y > 200) {
			doc.addPage();
			y = margin;
		}
		y = addSectionHeader(doc, "Anomaly & Deviation Report", margin, y);
		y += 5;

		const anomalyRows = anomalies
			.slice(0, 10)
			.map((a) => [
				a.label,
				a.type.toUpperCase(),
				formatNumber(a.value),
				formatNumber(a.expected),
				`${a.deviation > 0 ? "+" : ""}${a.deviation}%`,
				a.severity.toUpperCase(),
				String(a.zScore),
			]);

		doc.autoTable({
			startY: y,
			head: [
				[
					"Feature",
					"Type",
					"Value",
					"Expected",
					"Deviation",
					"Severity",
					"Z-Score",
				],
			],
			body: anomalyRows,
			margin: { left: margin, right: margin },
			styles: { fontSize: 7, cellPadding: 2.5 },
			headStyles: { fillColor: [244, 63, 94], textColor: [255, 255, 255] },
			alternateRowStyles: { fillColor: [255, 241, 242] },
		});

		y = doc.lastAutoTable.finalY + 15;
	}

	// --- Forecasts ---
	if (forecasts.length > 0) {
		if (y > 200) {
			doc.addPage();
			y = margin;
		}
		y = addSectionHeader(doc, "Predictive Forecasts", margin, y);
		y += 5;

		const forecastRows = forecasts.map((f) => [
			f.label,
			f.trend,
			`${f.growthRate > 0 ? "+" : ""}${f.growthRate}%`,
			`${(f.confidence * 100).toFixed(0)}%`,
			String(f.r2),
			formatNumber(f.forecast[0]?.predicted),
			`${formatNumber(f.forecast[0]?.lower)} – ${formatNumber(f.forecast[0]?.upper)}`,
		]);

		doc.autoTable({
			startY: y,
			head: [
				[
					"Metric",
					"Trend",
					"Growth Rate",
					"Confidence",
					"R²",
					"Next Forecast",
					"95% CI",
				],
			],
			body: forecastRows,
			margin: { left: margin, right: margin },
			styles: { fontSize: 8, cellPadding: 3 },
			headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255] },
			alternateRowStyles: { fillColor: [240, 253, 244] },
		});

		y = doc.lastAutoTable.finalY + 15;
	}

	// --- Correlations ---
	if (correlations.length > 0) {
		if (y > 200) {
			doc.addPage();
			y = margin;
		}
		y = addSectionHeader(doc, "Correlation & Dependency Analysis", margin, y);
		y += 5;

		const corrRows = correlations
			.slice(0, 8)
			.map((c) => [
				c.label1,
				c.label2,
				String(c.correlation),
				c.strength,
				c.direction,
			]);

		doc.autoTable({
			startY: y,
			head: [
				["Feature A", "Feature B", "Coefficient", "Strength", "Direction"],
			],
			body: corrRows,
			margin: { left: margin, right: margin },
			styles: { fontSize: 8, cellPadding: 3 },
			headStyles: { fillColor: [139, 92, 246], textColor: [255, 255, 255] },
			alternateRowStyles: { fillColor: [245, 243, 255] },
		});

		y = doc.lastAutoTable.finalY + 15;
	}

	// --- AI Insights ---
	if (insights.length > 0) {
		doc.addPage();
		y = addSectionHeader(
			doc,
			"AI-Generated Insights & Recommendations",
			margin,
			margin,
		);
		y += 5;

		insights.slice(0, 8).forEach((insight, idx) => {
			if (y > 260) {
				doc.addPage();
				y = margin;
			}

			doc.setFontSize(9);
			doc.setFont("helvetica", "bold");
			doc.setTextColor(...textPrimary);
			doc.text(`${idx + 1}. [${insight.category}] ${insight.title}`, margin, y);
			y += 5;

			doc.setFont("helvetica", "normal");
			doc.setFontSize(8);
			doc.setTextColor(...textSecondary);
			const descLines = doc.splitTextToSize(insight.description, contentWidth);
			doc.text(descLines, margin, y);
			y += descLines.length * 4 + 2;

			doc.setTextColor(51, 129, 255);
			const recLines = doc.splitTextToSize(
				`→ ${insight.recommendation}`,
				contentWidth,
			);
			doc.text(recLines, margin, y);
			y += recLines.length * 4 + 6;
		});
	}

	// Footer on all pages
	const totalPages = doc.internal.getNumberOfPages();
	for (let i = 1; i <= totalPages; i++) {
		doc.setPage(i);
		doc.setFontSize(7);
		doc.setTextColor(148, 163, 184);
		doc.text(
			`Yukti Decision Intelligence Report  |  Page ${i} of ${totalPages}  |  Confidential`,
			margin,
			doc.internal.pageSize.getHeight() - 10,
		);
	}

	doc.save(
		`Yukti_Intelligence_Report_${new Date().toISOString().split("T")[0]}.pdf`,
	);
}

function addSectionHeader(doc, title, x, y) {
	doc.setFillColor(51, 129, 255);
	doc.rect(x, y, 40, 2, "F");
	y += 8;
	doc.setFontSize(14);
	doc.setFont("helvetica", "bold");
	doc.setTextColor(15, 23, 42);
	doc.text(title, x, y);
	y += 8;
	return y;
}

function formatNumber(num) {
	if (num === null || num === undefined) return "-";
	if (typeof num !== "number") return String(num);
	if (Math.abs(num) >= 1e6) return (num / 1e6).toFixed(2) + "M";
	if (Math.abs(num) >= 1e3) return (num / 1e3).toFixed(1) + "K";
	return num.toFixed(2);
}
