import React, { useState } from "react";
import {
	Code2,
	Shield,
	Database,
	TerminalSquare,
	Server,
	Key,
	Webhook,
	Activity,
	ChevronDown,
	ChevronRight,
	Copy,
	CheckCircle2,
} from "lucide-react";

const ENDPOINTS = [
	{
		method: "POST",
		path: "/api/v1/integrations/auth",
		name: "Initialize Connection",
		description:
			"Exchange public keys and validate platform connectivity using supplied OAuth or API credentials. Establishes a secure tunnel for subsequent requests.",
		requestParams: [
			{
				name: "platformId",
				type: "string",
				desc: "Unique identifier for the POS/ERP (e.g., 'shopify', 'tally_prime')",
			},
			{
				name: "credentials",
				type: "object",
				desc: "Encrypted credential payload (AES-256)",
			},
		],
		responsePayload:
			'{\n  "status": "success",\n  "connection_id": "conn_8f72a91b",\n  "expires_in": 3600,\n  "scopes": ["read:transactions", "read:inventory"]\n}',
	},
	{
		method: "POST",
		path: "/api/v1/data/ingest",
		name: "Batch Data Ingestion",
		description:
			"Upload historical CSV/JSON data. Passes through Yukti's 6-layer pipeline: parsing, cleaning, schema inference, and anomaly detection.",
		requestParams: [
			{
				name: "dataset_type",
				type: "enum",
				desc: "'sales', 'inventory', or 'expenses'",
			},
			{
				name: "records",
				type: "array",
				desc: "Array of transaction objects (Max 10,000 per request)",
			},
			{
				name: "strict_validation",
				type: "boolean",
				desc: "If true, rejects entire batch on single schema failure",
			},
		],
		responsePayload:
			'{\n  "job_id": "job_batch_9921",\n  "status": "processing",\n  "records_accepted": 9850,\n  "records_rejected": 150,\n  "anomalies_detected": 12\n}',
	},
	{
		method: "GET",
		path: "/api/v1/analytics/forecast",
		name: "Retrieve Predictions",
		description:
			"Fetch polynomial regression forecasts generated by the Yukti AI engine. Includes confidence intervals and upper/lower uncertainty bands.",
		requestParams: [
			{
				name: "metric",
				type: "string",
				desc: "Target variable (e.g., 'daily_revenue', 'footfall')",
			},
			{
				name: "horizon_days",
				type: "integer",
				desc: "Forecast horizon (1 to 90 days)",
			},
		],
		responsePayload:
			'{\n  "forecast": [\n    {"date": "2024-11-01", "predicted": 45200, "lower_bound": 42000, "upper_bound": 48500},\n    {"date": "2024-11-02", "predicted": 47800, "lower_bound": 44100, "upper_bound": 51200}\n  ],\n  "model_used": "yukti-tinyllama-qlora-v2"\n}',
	},
	{
		method: "POST",
		path: "/api/v1/webhooks/register",
		name: "Register Webhook",
		description:
			"Set up a webhook endpoint to receive real-time anomaly alerts, sync completion events, or monthly diagnostic report generations.",
		requestParams: [
			{
				name: "target_url",
				type: "string",
				desc: "HTTPS URL to receive the POST payloads",
			},
			{
				name: "events",
				type: "array",
				desc: "List of event subscriptions (e.g., ['anomaly.critical', 'sync.completed'])",
			},
		],
		responsePayload:
			'{\n  "webhook_id": "wh_55x819",\n  "secret_key": "whsec_...",\n  "status": "active"\n}',
	},
];

export default function ApiReferencePage() {
	const [copiedId, setCopiedId] = useState(null);

	const handleCopy = (text, id) => {
		navigator.clipboard.writeText(text);
		setCopiedId(id);
		setTimeout(() => setCopiedId(null), 2000);
	};

	return (
		<div className="min-h-screen bg-[#0b1220] px-6 py-16 text-slate-100 lg:px-8 font-sans">
			<div className="mx-auto max-w-6xl">
				{/* Header */}
				<div className="mb-16">
					<div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-bold uppercase tracking-widest mb-6">
						<TerminalSquare size={14} /> Developer Documentation
					</div>
					<h1 className="text-5xl font-black tracking-tight text-white mb-6">
						API Reference v1.0
					</h1>
					<p className="text-lg max-w-3xl text-slate-400 leading-relaxed">
						Integrate directly with Yukti's 6-layer predictive engine. Use our
						RESTful APIs to sync live POS data, extract AI-generated anomaly
						reports, and build custom business intelligence dashboards.
					</p>
				</div>

				{/* Architecture Cards */}
				<div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4 mb-16">
					{[
						{
							title: "Authentication",
							icon: Shield,
							desc: "Bearer token auth via Firebase. Tokens expire every 1h. Requests without valid tokens return 401 Unauthorized.",
						},
						{
							title: "Rate Limiting",
							icon: Activity,
							desc: "1,000 requests/minute per IP. Batch data endpoints are limited to 50 concurrent jobs per workspace.",
						},
						{
							title: "Data Storage",
							icon: Database,
							desc: "All transactions are written to tenant-isolated Firestore collections. Retained for 7 years for compliance.",
						},
						{
							title: "Encryption",
							icon: Key,
							desc: "AES-256 server-side encryption for all stored credentials and PII. TLS 1.3 mandated in transit.",
						},
					].map((feature, idx) => (
						<div
							key={idx}
							className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 hover:bg-slate-900/80 transition-colors"
						>
							<div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
								<feature.icon size={20} />
							</div>
							<h2 className="text-base font-bold text-slate-100 mb-2">
								{feature.title}
							</h2>
							<p className="text-sm text-slate-400 leading-relaxed">
								{feature.desc}
							</p>
						</div>
					))}
				</div>

				{/* Endpoints Section */}
				<div className="space-y-8">
					<h3 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-800 pb-4">
						<Server size={24} className="text-cyan-400" /> Core Endpoints
					</h3>

					{ENDPOINTS.map((ep, idx) => (
						<div
							key={idx}
							className="rounded-2xl border border-slate-800 bg-slate-900/40 overflow-hidden"
						>
							{/* Endpoint Header */}
							<div className="border-b border-slate-800 px-6 py-5 bg-slate-900/80 flex flex-col md:flex-row md:items-center justify-between gap-4">
								<div>
									<h4 className="text-lg font-bold text-white flex items-center gap-3">
										{ep.name}
									</h4>
									<p className="text-sm text-slate-400 mt-1">
										{ep.description}
									</p>
								</div>
								<div className="flex items-center gap-3 bg-black/50 p-2 rounded-lg border border-slate-800 font-mono text-sm self-start md:self-auto">
									<span
										className={`px-2 py-1 rounded font-bold text-xs ${ep.method === "POST" ? "bg-emerald-500/20 text-emerald-400" : "bg-blue-500/20 text-blue-400"}`}
									>
										{ep.method}
									</span>
									<span className="text-slate-300">{ep.path}</span>
								</div>
							</div>

							{/* Endpoint Body */}
							<div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-800">
								{/* Parameters */}
								<div className="p-6">
									<h5 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-4">
										Request Parameters
									</h5>
									<div className="space-y-4">
										{ep.requestParams.map((param, pIdx) => (
											<div
												key={pIdx}
												className="bg-slate-900/50 rounded-lg p-3 border border-slate-800/50"
											>
												<div className="flex items-center gap-2 mb-1">
													<span className="font-mono text-sm text-cyan-300">
														{param.name}
													</span>
													<span className="text-xs font-medium px-1.5 py-0.5 bg-slate-800 rounded text-slate-400">
														{param.type}
													</span>
												</div>
												<p className="text-sm text-slate-500">{param.desc}</p>
											</div>
										))}
									</div>
								</div>

								{/* Response Example */}
								<div className="p-6 bg-[#0f172a]">
									<div className="flex items-center justify-between mb-4">
										<h5 className="text-xs font-bold uppercase tracking-wider text-slate-500">
											Response Example (200 OK)
										</h5>
										<button
											onClick={() => handleCopy(ep.responsePayload, idx)}
											className="text-slate-500 hover:text-white transition-colors"
										>
											{copiedId === idx ? (
												<CheckCircle2 size={16} className="text-emerald-400" />
											) : (
												<Copy size={16} />
											)}
										</button>
									</div>
									<pre className="text-sm font-mono text-slate-300 overflow-x-auto whitespace-pre-wrap">
										<code>{ep.responsePayload}</code>
									</pre>
								</div>
							</div>
						</div>
					))}
				</div>
			</div>
		</div>
	);
}
